// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhntdjgfymodljkhykfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobnRkamdmeW1vZGxqa2h5a2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzAzNTgsImV4cCI6MjA2NDI0NjM1OH0.FWeo5RrTWi3DoKgj-KgyCjrc5sp_ordoK3q8hvz96nY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);